apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "crane.konveyor.io/v1alpha1",
          "kind": "OperatorConfig",
          "metadata": {
            "name": "openshift-migration"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    console.openshift.io/plugins: '["crane-ui-plugin"]'
    operatorframework.io/suggested-namespace: openshift-migration-toolkit
    operators.operatorframework.io/builder: operator-sdk-v1.15.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: crane-operator.v99.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OperatorConfig is the Schema for the operatorconfigs API
      displayName: Operator Config
      kind: OperatorConfig
      name: operatorconfigs.crane.konveyor.io
      version: v1alpha1
  description: migration toolkit for Red Hat OpenShift
  displayName: crane
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAGoNJREFUeJzt3XlcE2f+B/DPJCEHQoIgp6KCB4IHWm+tVq26Vunhere1alt72K5tbbu72t2u/qy6rbf1WFu1dV0t7bauB1rPar2KWOqJiiJQLxQQIUBOkvn9EZhkSBhCkCSa7/v18iUzmUweknx45pnnmXmYrt3msCCEOCTydAEI8WYUEEIEUEAIEUABIUQABYQQARQQQgRQQAgRQAEhRAAFhBABFBBCBFBACBFAASFEAAWEEAEUEEIEUEAIEUABIUQABYQQARQQQgRQQAgRQAEhRAAFhBABFBBCBFBACBFAASFEAAWEEAEUEEIEUEAIEUABIUQABYQQARQQQgRQQAgRQAEhRAAFhBABFBBCBFBACBFAASFEAAXEiygUfhg+vBMe69LC00UhlSSeLgCx6NSxGebMeQ7R0cEAgPx8NUaNXgWt1ujhkvk2qkE8zM9PjGnTBmHduilcOAAgLEyJzZtfR/v2TT1YOiKOiho429OF8FWtW4dhxYoXMPjJBDAMY/e4SqXAs890AQvg7NkbYFma0t7dqAbxAJGIwUsT+2DTv6eibZtw3mMVFWaYTGbetm+8PgBffjEJTZs2dndRfR4FxANmzUzC9OmD4ecn5tYZDCawLAuJRASxWGTX9ujUKRr/2TQVYaGB7i6uT6OAeECfPq14yzqdEVKpmHeYpVD4wWzmH1IFBsqpTeJmFBAPOHw4k7dsW5PYEon47RK1Wov033IbqljEAQqIB6xbfwQajYFbrqgwO9xOqzXwlleu+glqta5By0b4KCAeUFRUjq83HueWZTIJKipMdtspFFLu58uX87Bt229uKR+xooB4yJYtqcgvKLVZwz+cql57fPbZj3ZtEtLwKCAeotMZ8a81h7hliUQEna4CAGAymXm1R0rKWZw7f9PtZSQUEI9K2XUWWVn53LJMZmms29YU5eV6fL7yoNvLRiwoIB5kNrNYseIAt1x1mtf2rNbatYdx716Z28tGLCggHvZLahbSTuU4fCw7uwDf/feUm0tEbFFAPIxlgeXL9zt87OjRK7xhJ8T9KCBeIDPzDn7//Z7d+kmT+mLZ0glo3NjfA6UiAAXEa3z8j20O1/ft2wbr101BcHAjN5eIADTc3WsUFJTi5s0i9OgRi4yM2xBLRGjUSAYAUKn8kZAQhd27z4FGvLsX07XbHHrLvZBUKsHMmSPwdFIit27WRz9g374MD5bK99AhlocolQo4uEaKYzBUYN68nbh+3do2GTO6uxtKRmxRQNyMYYD580bhp4MfYuPGV6FQ+NW4bUWFGXv2XuCWExOjIZU6HvlLGgYFxM3CwpQYOrQ9ACAhPgrdu8UIbp93u5j7WSRiEBREjXV3ooC4mV5fwVtuYnOFYHBwI7w0sQ/69G7NrQtUKnjbazT6hi0g4aGAuFlJiQZ5eSXcct8+1jB8vuIFTJ8+GCtWPI/XXx8AhuE/fv1GEcrKKCDuRAFxM5YFdu06yy0/8UQcBg2KB8MAMTGh3Pqpr/bHv9a8hJ49Y7l1ts8j7kGneT1AqZTj+/++xXX+sSywM+UMRAyDJJvTurbyC0oxZsxqlJdTDeJOVIN4gFqtw6yPfuAutWUY4JmnO9cYDpZlMW9eCoXDAyggHvLrr7mY/s4WqNXaWrdlGAbvzxiKqKggN5SM2KKhJh50504Jduw4A5ncDwkJTXkdhxUVJhiNZkgklr9hKpU/hg5tj1Oncuj6EDeiNogHKJVyLFk8Hp06RWPLllQsW74ffn5idOzYDL16tcKJE1m4cOEmoqIaY+XKFxAVaa05NBoDPvjwO6SlZXvwN/AdFBA38/eXYs3qibwbwA168rMab+cTEhKAFcufR1xcBLfOZDJj9uzt+HHP+QYvr6+jNogbyeV+WLZsAi8ct27dF+zbuHevDFNf+xonT1prDLFYhLlzR2Lii70Fx3OR+qM2iJtIpWIsWjgOPbpbh5YUFZVj2lubUFysEXyu0WjC/v0ZiIpqjDY2N7vu1asVAgLkOHkym4bBNxAKiBtIJCIsmD8a/fq15dap1Tq88ea/kZNT6NQ+zGYWP/+cCZnMD4mJ0dz6jh2boWVMKI4ezYTJRCl50CggDUwkYjBn9kgMHpzArdNoDJj21iZkZt6p075YFjiZlg11qRa9e7fmDq9axYaic+fmOHz4MgwG+zs0EtdRG6QBMQwwc+YIDBvWgVun11fgnXe34OLF2y7vNzk5DTNnfQ+j0RqGrl1bYt2XU2h6hAeMAtJAGAaYMeMPGPncY9w6o9GEGe8n4/Tp6/Xe/4EDF/H2nzbzGvitW4dhw4aXERPTpN77JxYUkAbyxusDMWF8T27ZbGbxl79+zzsbVV/p6bl4depXvHv8RkSosH7dy7x2CnEdBaQBTJ7cF6+80o9bZlngb3/fiiNHMgWe5ZqsrHxMmbIe2TkF3DqlUo41qydiwIB2D/z1fA010h+wceN64L13h/LWzf1kB3bvbrhOvfJyPfbuzUBiYjQiIlQALH0lgwcnoOh+OS5dymuw137UUUAeoGee6YxZM0fw1i1ctAdbt6Y3+Gvr9RXYs/cCYmKbcNeVMAyDfo+3hVgsQnp6boOX4VFEAXlAhg5tjzmzR/J6tleuOojNm1PdVgaTyYyDBy9BFeTP661/7LEWiAhX4fiJqzTHSB1RQB6A/v3jsGD+KN6cghs2HMWX6464vSwsC5w4kQWjwYQePay99nFxEWjXLhIHDl6kkNQBBaSeevaMxeJF4yCRWG/Hs+Wbk/h85QGBZzW8M2eu43ZeMfr3j+OmVWjePAQZF2/z7rVFhNFZrHro0qU5liwez5vPY9u201i6dK9XjI1KSTmLj//xP966sDDqSKwLCoiLEuKjsHzZ85DJJNy6PXsuYP6CFI+FQyxmEeBvQrDSemuh6rcqVanoTvF1Ial9E1JdaGggVq58Af7+1nkEDx++jNlztj2Q43uGAeRSMxSyyn9yM+QyExQyFv4yE+QyMxRyFgqZCf4ys2VbOQs/iXUukW2Hg3Epxx9mM4viYg2CgizBqPqfOIcC4oLExGgobW7oduXqXd5NGGxJ/czwl7GWL3Xll9tfboZcZvmCK7j/rYGQSc31vs4jKNA6TqukRGsNiEpR01OIAxQQF2g09lM0GwwmBKuMGNa7GI0Uli+8XMpCLPbM8ZZCZg1rcbEGLVqEAKAapK4oIC4oK+VfHiutbKRHhBjRItI7bs1jG5CSEusFWSqqQeqEGukuUFcLSNX9c3V673k7+TWI9dZCVIPUDdUgLiitHpBAy0xQWp1rUxOwLKA3iKDRi6DTi6DVi6DVi6HTM9DqRdAbRIhroUV0hPO1k0JmbYPYXtJLZ7HqhgLiguoBUQZaahCNvm4ta5OJwbf7m+D6HVmtp4YzshV4Z4Lzgw7lMusOi20OsQICZJBIRA5PKBB73nNM8BAxGCpgMFj7GgIC5QAAnaFub2dxmRi/59UeDgAIDzbWad8KOb+RbkuppHaIs6gGcZFarUOTJgEAAGVlQPQGEcwsIHKyIglRVaBnh1LcLpRy/R7+tn0fcjPX1xGiqtu15gqpbSOdf3vToCB/FBWV12l/vooC4qLSUmtAAisDAgBanQiNFM4fvgzqXlL7Ri4QiVhI/VgYjIxdDRJE7RCn0SGWi0pLrX+VA5XWgNT1MKshVTXUHdUgxDne82k+ZGwb6oEBNjWI3nsm2axqh1SvQagvxHkUEBeVllpPudo2erU677kXqKLyTJZareWdCKAaxHkUEBepbQ+xAr20Bqk8xDKbWd4hIdUgzqOAuMh2uElgoJwbXKitY19IQ+L1ppdQb7orKCAush1u4ucnhlRqOSGo86oaxHFfCNUgzqOAuMh+uInlMMtba5ASm4BQDeI8CoiLStU1DDdxcTxWQ+D1ptscYqkoIE6jgLiotIwfEFeHmzQkXm+6bQ1CHYVO855P8yFTfXZapbLqEMt73lJ+I90akMBAOcRi7ymnN6N3yUV2bZDKzkKtznveUrnctgaxBpphrIEmwrzn03zI2AWk8gun8dYaxK43nQ6znOE9n+ZDprxcz+udrjqLZTIxqDB5x5ksmR8LhrEUksZjuYYC4iKzmUWZTUO96iwW4D3tEIZhuQunaDyWa7zjk3xI2Z7Jsh1u4l2HWZbhJraNdIBqEGd5zyf5ELLtC+ENefeihrrtgEVbVIM4x3s+yYdQzUPevedtrWqoV1SYefMZUg3iHO/5JB9CtiN6bU+betXtf2q4Np06C53jPZ/kQ6jM5pqQAF4bxIuGm8hsb0FqOx6LDrGcQQGpB9vjetuzWF5Vg9je/ofuj1Vn3vNJPoRsz2I1aiTjZpjyqqsKa7i7CbVBnEMBqQfbs1gMY7kpG+BtjfSa7rBIh1jO8J5P8iFUfbhJQEDVcBPvaYPIa7iqUKlU8OZUJI5RQOqh+k2slV55E2vHbRCRiOECTWpGN46rB2+7qlBvEEFnEEGjZ6DViaHViXDtljUEjsZjVe9AJHwUkHqoPk+INSAisCzDDRSsK5OJgUYvglZnudO7ziCCRieGVs9Ap7f8r9WLodVZ/tcZLNvWNvub3R0Wg/xpxttaUEDqwbajELAGhGUZ3CuRIERVUTmVAQOdXgSNXmxZ1lmXdZUB0Got0x9o9aIGGw1cUn08FjXUa0UBqQf7aRCshzPrtoUDYMGyDfNll0olCFIpoFQpoFQqoFIqoAqy+VnlD6VKDpWycl2QP8JC+VNA06ne2lFA6kGvr4DBYIJUajlrZTui13KtSO3hcOWLrlIqeNNPuyqQriqsFQWknsrKdAgObgQAiI0NRevWYW7/orvCZDLj9G/XPfLaDxMKSD2p1VouIAMGtMOAAe08XCJApzOipESLErUW6hItSko0KFHroC7RQq3WorhEg/PnbyInp9DTRfV6FJB6qt4OeZCc+aKrK5ctP2uhVut4s1+R+qGA1NO5czfRsWMzwW3oi/7wooDU08pVB5GdUwCVUkFf9EcQBaSejEYTtm8/7elikAbiPYOGCPFCFBBCBFBACBFAASFEAAWEEAEUEEIEUEAIEUD9IDWQSiXo3bsVQkMDcf33e/g1PRfm2q5IeuBlEKNXz1YID1fi+o0inDqV4/Yy+DqfDsiqlS8iOLgRJjy/Ft26tcSfP3wKWdfysXlzKj77dAzCw5XctpmZd/DejGQUF5fjP5tew4WMW5g7dwdYFlix4nlEhKuwfMUBvDN9MPbvz8CX645AofDDhvUvo7hYg5RdZzHppb681//66+OYPLkvrmUXYObM7xESEoDVq15Efn4pVq46iEULxyEyUsVtf/XqXcx4Pxnl5Xqs+3IKt16t1mLtFz/j1Kmchn/TfIxPH2I1bx6CVq3CEBGhwj8XjEaTJgH4+qtjWLpkPMLClNi+/TTmL9iFI0evIC4uAosWjQXDMIiNDcUzT3fG5EmPW/YTHYLY2FCcPv07oqKCkJSUCIYBuneLQZs24bialQ+VUoHY2FAoFFJoNAZoNAbczivGnbslGDI4Aa1bh+GPIx9Dq1ZhOH4iC8uWTkBkpAo7U85i/oJd+PnnTLRpE47Fi8dDIhEjNjYUkZFB0GoNSEhoiqVLxnOjismD49MBAQCGYbBo4VgolQr89a/fo0OHpggOboQtW1Ix95Od2Lo1HTNmJOPEL1lIiI/iDUycNm0QevVqxS1rNAb8dOgymjZtjBYtmuDxfm0BALt2neW2OXrsClavOYRly/fjzJnrWLv2ZwDA+HE9MXp0N9y+XQy93ojQ0ED89/tfMWfOdmzdmo73P/gWx45dRds24UhMjAYAXLuWj0mT12PfvguQy/0QHx/ljrfMp1BAGKBdu0jcvavGufM30Sw6GACQevIab7vU1GwAQHSzxgAArdYIlmUxf94o7nY/AJCSYglD/35t0e/xNrh2LR9XrtzhHh87pjtWr3oRc/9vJAAgI+MWjhy9guee64KQkACs/eIwoqKCKl+TX4ZfKpebNbWUITY2FBvWT8GQIe1hNJp4r0MeDJ8PCACkp+ciMlKF994dijt3SgAAnTpF87bp3NmyfOeuGgCQl1eMlSsPQqmU8+7s/uuvOcjPV2PChJ4IDQ3Erl3neFO1JSen4fU3/o1ZH/3ArVu//igA4Nat+/jxx/PIy7OUIdGuDM0BAHfzLWXw8xOjZctQyGQSJH+bhoKC0nq/F4TP5wNiNrN4c9omXLhwC6NGdUWpWofSUh1envI43n7rSQwc0A4ff/wMBg2MR05OIU6ftl6muuk/J7B37wW7/e3afQ6hoYEwm1n8uOc87/Fu3Vri+Qk9MXlSX/TsGQsAXCjv3lXDbGZx4MBFqNVavPhib0yfPhgDB7TD3//2NIYMTsCNG0X47bffAVhOHLw69SuYzSyGP9UR/v7ShnyrfJJPB6S8XI+yMh3MZhaz52xHcbEGU197ArPnbEd5uR6TJ/fFwoVj8czTnXHr1n18+OfvKucm1HOTeM79ZCfOnb/Jm5wmJeUsysr0OHbsCvdX3WA0oaxMj4gIFbp2bYmuXVuiSZMAAADLWvap0RgAWM5KffDBdygt1eGliX2wcOFYPPtsF9zOK8b7H3wLY+W+NFoDsrML8O13aZDJ/DB2bHf3v4mPOKZrtzl0Yt0BpVKOQYPiERamRG5uIQ4fznT7hU+BgXIMHNgOEREqXL9+D4cOXYZeTxdfuRMFhBABPn2IRUhtfLonvTqGAeLbRaFzl+aIjFRBLBLh/v1yXLqch7S0HLtDrGHDOqBp5SlXRwoLy3D8+FUUFpbV+tojn3sMwSHWjr6DBy8hN9f+tjwiEYMpUx7nls+fv4W0tGy77WJjQzFwoPUWRGYTi6++PgYAiIlpgkGD4mstEwDkZBfip0OXnNr2UUQBqdSjewzeeWcI4uIiHD5eUqLF+g1HkZx8khsPNWJ4Inr3buVw+yoVFWZs3Hgca784XOM4qtDQQMycOYI3X0d4uArz56fYbcswDN58YyC3bDBUYOprG5GRcYu3XevWYdW2M3EBiY3lPyZk3/4Mnw4IHWIBePnlfli9emKN4QAsMzLNeG8oPvt0DMRi5982iUSEV17ph7/8eXiN2zw1rKPdZDZDh7SHVFr73y+pVIIli8fxxo2RB8fnAzJ6dDdMe9O5v6aA5e6Jw4Z1qPPrjBrVFV27trRbzzBAUlKi3fqAABn692/r1L5DQgKwdOkE6gdpAD59iBUaGoj33h3KW1dSosXiJXtx7NhVmExmJCRE4c03B6JTx2YoL9djydJ92L37nMP97dhxBosW7wEAhIcr8a81LyEkJIB7/OmkRKSn5/KeExcXidjYUIf7SxqRiAMHLjr1u7RtE45P5o7EBx9+V+ch8WYziwEDP3X4WEWF2eF6X+HTNchzz3bh3TzabGbxp+mbsXv3OajVWpSX63HqVA7eemsTtm07jbHj1mD79tO8oSO2KipM3EjdnJxCnPiFP5YqunKcl62kEfza47fTv3M/9+nTuk4jdPv3j8Pbbz/p9Pa2qspd/Z+v3/TOp2uQqqEeVVJPXsPFi7ftttNqjfhk3s467VssFqFtm3DeupJq051JJCLe4dqVK3eQnJyGx7q0AGA5YzXsDx2w5ZuTTr/uSxP7IDe3EDqd0enniEQMdu54x2596slrmDfP/kSBL/HpgIRVa9hmZtZvNOygQfHckHNVkAJRkUG8x385kcVb7tOnDW8Sm0OHLiM19RqMRhP8/CxzjiQlJdYpIADw0awkbNtWt7s92l6YVSW4MV1f4tOHWHod//DBT1K/6ZuDgvwRHx+J+PhIu3Dk5hZix84zvHVJIzrxln86dBkajYF3ZWDbthFoU60mqm7r/37jHfaJxSKMGtXVxd+C2PLpGuRq1l3ExDThlrt3jwHDoMY2hquu3yjC9OlbeOOolEoF+vWznqUqK9OjeXQwoqODUVRUznv+iOGdsGz5/hr3f/ToFWRn5+OD94e5VD6WBf756S679Xm3S1za36PEpwOyf18Ghg5pzy3HxUXg2We72B2eNG3aGPPn/RFfrjuC48ev1higgoJS5OQWol1cBO8iKrlMguJqE2j+YWh77jAKsJzWXbhwrMP9PvVUR3y+8iBMpprPKCUnpyG6WTDGjetR4zY1YVkWP/yQXufn+QKfDsjPRzJx5epdXmP6o1lPIy4uEod+ugSD0YSEhChMntQXwcGNsGzpBKSdysGypftw5epdu/0dPXoF8xfswuDBCfjngtHc+rAwJaZOfQLLbWqBESPs+z5qEhISgJ49YnHilyzB7RYv2YuoqCBezeQMhmHQo0esw8f0eiPOnr1Rp/09Snw6IGYzi48//h82rH+Z62RjGGDM6G4YM7qbw+f06B6D7j1iHAakysGDF5Gaeo13vfoLz/dCSspZXLuWjxYtQtChQ1PecxYt3sM78zR0SHvelzYpKbHWgJjNLD7621Z8+cVkwVEB1TEMsHrViw4fu3nzPp4b+bnT+3rU+HQjHQCysvLx9p824/59Te0bA9i8ORXf1HJWiWWBTz/7EQaDiVsnEjGY+dfhEIkYu57zi5duIzk5Ddu2neb+VT9zNWBAHAICZLWWT6Mx4N33vkF+5WW5pH58PiAAcO7cDYwbvwY//JDusGPMbGaRmnoNr72+EUuX7XOqp/rGjSJ8vfEYb13nzs2RNCIRI4ZXO3v1k/1gwJMns3lXKUqlEjz5ZIJTv09BQSneffcb7gpF4jq6YKoahcIPHTo0Q1hYIBiGQUFBKS5dyoO6WicfYGnUq1TWfoyCAjVv5lipVMLdaKGKQV8BabWpny9fdrz/+PhIBAZaG/uFhaXIzS1Et24xvO2uXr3jsAZs2bIJwsIsfT0sy3Knj4ODG6F1a+FTx1V8vQ1CASFEAB1iESKAAkKIAAoIIQIoIIQIoIAQIoACQogACgghAigghAiggBAigAJCiAAKCCECKCCECKCAECKAAkKIAAoIIQIoIIQIoIAQIoACQogACgghAigghAiggBAigAJCiAAKCCECKCCECKCAECKAAkKIAAoIIQIoIIQIoIAQIoACQogACgghAigghAiggBAigAJCiAAKCCECKCCECPh/JpiwiAuUijYAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - console.openshift.io
          resources:
          - consoleplugins
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - crane.konveyor.io
          resources:
          - operatorconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - crane.konveyor.io
          resources:
          - operatorconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - crane.konveyor.io
          resources:
          - operatorconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - tekton.dev
          resources:
          - clustertasks
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: crane-operator-controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
        serviceAccountName: proxy
      deployments:
      - name: crane-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: CRANE_RUNNER_IMAGE
                  value: quay.io/konveyor/crane-runner:latest
                - name: CRANE_UI_PLUGIN_IMAGE
                  value: quay.io/konveyor/crane-ui-plugin:latest
                - name: CRANE_REVERSE_PROXY_IMAGE
                  value: quay.io/konveyor/crane-reverse-proxy:latest
                - name: CRANE_SECRET_SERVICE_IMAGE
                  value: quay.io/konveyor/crane-secret-service:latest
                image: quay.io/jgabani/crane-operator-container:latest
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: crane-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: crane-operator-controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
        serviceAccountName: proxy
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - crane
  links:
  - name: crane Operator
    url: https://crane-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  relatedImages:
  - image: quay.io/konveyor/crane-runner:latest
    name: crane-runner
  - image: quay.io/konveyor/crane-ui-plugin:latest
    name: crane-ui-plugin
  - image: quay.io/konveyor/crane-secret-service:latest
    name: crane-secret-service
  - image: quay.io/konveyor/crane-reverse-proxy:latest
    name: crane-reverse-proxy
  version: 99.0.0
