apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: crane-secret-service-certs
  labels:
    app: crane
    service: secret-service
  name: secret-service
  namespace: openshift-migration
spec:
  ports:
  - name: port-8443
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: crane
    service: secret-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crane
    service: secret-service
  name: secret-service
  namespace: openshift-migration
spec:
  selector:
    matchLabels:
      app: crane
      service: secret-service
  template:
    metadata:
      labels:
        app: crane
        service: secret-service
    spec:
      containers:
      - env:
        - name: GIN_MODE
          value: release
        - name: CRANE_SECRET_SERVICE_CRT
          value: /certs/tls.crt
        - name: CRANE_SECRET_SERVICE_KEY
          value: /certs/tls.key
        image: quay.io/konveyor/crane-secret-service
        imagePullPolicy: Always
        name: secret-service
        ports:
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - mountPath: /certs
          name: crane-secret-service-certs
      volumes:
      - name: crane-secret-service-certs
        secret:
          defaultMode: 256
          secretName: crane-secret-service-certs
